#!/usr/bin/env python3
"""Test double for gpg: records the call in $FAKE_AZ_LOG as ["__gpg__", ...]."""
import json, os, sys
with open(os.environ["FAKE_AZ_LOG"], "a", encoding="utf-8") as log:
    log.write(json.dumps(["__gpg__", *sys.argv[1:]]) + "\n")
sys.exit(0)
